import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/organisms/Header";
import { SidebarProvider } from "@/components/providers/SidebarProvider";
import Footer from "@/components/organisms/Footer";
import Sidebar from "@/components/organisms/Sidebar";
import Auth from "@/components/organisms/auth/Auth";
import MainContent from "@/components/organisms/MainContent";
import Bottombar from "@/components/organisms/Bottombar";
import AuthModal from "@/components/Modal/AuthModal";

const montserrat = Montserrat({
  subsets: ["latin"], // Specify the character subsets you need
  weight: ["400", "700"], // Define the weights you want to use
  variable: "--font-montserrat", // Optional: Define a CSS variable for easier use with Tailwind CSS
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}  antialiased`}>
        <SidebarProvider>
          {/* <Auth /> */}
          <Header />
          <main className="flex pt-14 bg-[radial-gradient(circle_at_50%_322px,_#003A81_154px,_#0D131C_300px)] relative ">
            <Sidebar />
            <div className="main-content ">
              <MainContent />
              {children}
              <Footer />
            </div>
          </main>
          <Bottombar />
          <AuthModal />
        </SidebarProvider>
      </body>
    </html>
  );
}
