import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/providers/SidebarProvider";
import { ModalProvider } from "@/components/providers/ModalProvider";
import { BottomBarProvider } from "@/components/providers/BottomBarProvider";
import { LoadingProvider } from "@/components/providers/LoadingProvider";
import { ProfileProvider } from "@/components/providers/ProfileProvider";
import { LanguageProvider } from "@/components/providers/LanguageProvider";
import LayoutContent from "@/components/LayoutContent";

const montserrat = Montserrat({
  subsets: ["latin"], // Specify the character subsets you need
  weight: ["400", "700"], // Define the weights you want to use
  variable: "--font-montserrat", // Optional: Define a CSS variable for easier use with Tailwind CSS
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}  antialiased`}>
        <LoadingProvider>
          <SidebarProvider>
            <ModalProvider>
              <BottomBarProvider>
                <ProfileProvider>
                  <LanguageProvider>
                    <LayoutContent>
                      {children}
                    </LayoutContent>
                  </LanguageProvider>
                </ProfileProvider>
              </BottomBarProvider>
            </ModalProvider>
          </SidebarProvider>
        </LoadingProvider>
      </body>
    </html>
  );
}
